print(""
      "Here is the Plane seating chart\n"
      "1:   + +    + + \n"
      "2:   X +    + + \n"
      "3:   + +    + X \n"
      "4:   + +    + + \n"
      "5:   + +    + + \n"
      "6:  + X +  + + +\n"
      "7:  + + +  + + +\n"
      "8:  + + +  + + X\n"
      "9:  + + +  + + +\n"
      "10:   X +  + +  \n"
      "11: + + +  + + +\n"
      "12: + + +  + + +\n"
      "13: + + +  X + +\n"
      "14: + X +  + + +\n"
      "15: + + +  + + X\n"
      "16: X + +  + + +\n"
      "17:   + +  + X  \n"
      "18: + X X  + + X\n"
      "19: + + +  + + +\n"
      "20: + X +  X X X\n"
      "First five rows are first class\n"
      "Rows 10 and 17 are exit rows\n"
      "Seats marked with an X are taken\n")


